- hosts: firewall
  remote_user: root
  tasks:
    - name: Setup IP forwarding in kernel
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
