- hosts: 127.0.0.1
  tasks:
    - name: Wait for DC2_corp Provisioning and boot to complete
      wait_for:
        host: 172.16.1.6
        port: 5985
        delay: 15
        sleep: 15
        timeout: 1200

- hosts: 172.16.1.6
  gather_facts: true
  tasks:
    - name: Set DNS servers
      win_dns_client:
        adapter_names: "*"
        ipv4_addresses:
          - 172.16.1.5
    - name: Install GPMC
      win_feature:
        name: GPMC
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install Backup-Features
      win_feature:
        name: Backup-Features
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install Backup
      win_feature:
        name: Backup
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install Backup-Tools
      win_feature:
        name: Backup-Tools
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install DNS and WINS
      win_feature:
        name: DNS,WINS-Server
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install AS-Net-Framework
      win_feature:
        name: AS-NET-Framework
        state: present
    - name: Install Domain Services
      win_feature:
        name: AD-Domain-Services,ADDS-Domain-Controller
        state: present
        restart: true
    - name: Check Registry
      win_reg_stat:
        path: HKLM:\System\CurrentControlSet\Control\ProductOptions
        name: ProductType
      register: dc_reg
    - name: debug
      debug:
        var: dc_reg
    - name: Run DCPROMO to create domain
      win_command: dcpromo.exe /unattend /InstallDNS=yes /Username="bank\administrator" /Password="Sh73PJ8eK4n4wH3a6hPQTJZq" /UserDomain=bank.local /ReplicaDomainDNSNAme=bank.local /ReplicaOrNewDomain=replica /ForestLevel=4 /DomainLevel=4 /ConfirmGC=Yes /SafeModeAdminPassword="yrHVEvwMBRubYNXbDf4gS" /RebootOnCompletion=yes
      register: dc2_promo_result
      changed_when: "dc2_promo_result.rc <=10"
      failed_when:
        - dc2_promo_result.rc >= 11
      when: dc_reg.value == "ServerNT"
      retries: 3
- hosts: 127.0.0.1
  tasks:
    - name: Wait for DC2_corp reboot to finish
      wait_for:
        host: 172.16.1.6
        port: 5985
        delay: 30
        sleep: 30
        timeout: 600
- hosts: 172.16.1.6
  vars:
    ansible_user: bank\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: false
  tasks:
    - name: Testing Connectivity to DC2
      win_ping:
    - name: Set DNS servers
      win_dns_client:
        adapter_names: "*"
        ipv4_addresses:
          - 172.16.1.5
          - 172.16.1.6
    - name: Reboot to force DNS
      win_reboot:
