- hosts: dc1_corp
  vars:
    domainname: "mercytechhealthcare.local"
    domainnetbios: "mercy"
    domainadmin_user: "administrator"
    domainadmin_pass: "ZphYKNXgSWeJ54bJU9HP"
    safemodeadmin_user: "admin"
    safemodeadmin_pass: "ngrUuLzc6xV4g97426Bt" 
  gather_facts: true
  tasks:
    - name: Create Temp folder
      win_file:
        path: c:\temp
        state: directory
    - name: Copy Domain Create Powershell Script
      win_copy:
        src: ../files/Install-TAFirst2008R2DomainController-0.8.ps1
        dest: c:\temp
    - name: Run powershell to create domain
      win_shell: c:\temp\Insall-TAFirst2008R2DomainController-0.8.ps1 -Domain mercytechhealthcare.local -NetBiosDomainName mercy
           
