- hosts: 127.0.0.1
  tasks:
    - name: Wait for DC1_clinical Provisioning and boot to complete
      wait_for:
        host: 172.16.3.10
        port: 5985
        delay: 15
        sleep: 15
        timeout: 300
- hosts: dc1_clinical
  gather_facts: true
  tasks:
    - name: Set DNS servers
      win_dns_client:
        adapter_names: "*"
        ipv4_addresses:
          - 172.16.1.50
          - 172.16.1.51
    - name: Install GPMC
      win_feature:
        name: GPMC
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install Backup-Features
      win_feature:
        name: Backup-Features
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install Backup
      win_feature:
        name: Backup
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install Backup-Tools
      win_feature:
        name: Backup-Tools
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install DNS and WINS
      win_feature:
        name: DNS,WINS-Server
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install AS-Net-Framework
      win_feature:
        name: AS-NET-Framework
        state: present
    - name: Install Domain Services
      win_feature:
        name: AD-Domain-Services,ADDS-Domain-Controller
        state: present
        restart: true
    - name: Check Registry
      win_reg_stat:
        path: HKLM:\System\CurrentControlSet\Control\ProductOptions
        name: ProductType
      register: dc_reg
    - name: debug
      debug:
        var: dc_reg
    - name: Run DCPROMO to create domain
      win_command: dcpromo.exe /unattend /ParentDomainDNSName=mercytechhealthcare.local /InstallDNS=yes /Username="mercy\administrator" /Password="Sh73PJ8eK4n4wH3a6hPQTJZq" /UserDomain=mercytechhealthcare.local /ReplicaorNewDomain=domain /ChildName=clinical /DomainNetBiosName=CLINIC /ForestLevel=4 /DomainLevel=4 /ConfirmGC=Yes /SafeModeAdminPassword="yrHVEvwMBRubYNXbDf4gS" /NewDomain=child /CreateDNSDelegation=yes
      register: dc1_promo_result
      changed_when: "dc1_promo_result.rc <=10"
      failed_when:
        - dc1_promo_result.rc >= 11
      when: dc_reg.value == "ServerNT"
- hosts: 127.0.0.1
  tasks:
    - name: Wait for DC1_clinical reboot to finish
      wait_for:
        host: 172.16.3.10
        port: 5985
        delay: 30
        sleep: 30
        timeout: 600
- hosts: dc1_clinical
  vars:
    ansible_user: mercy\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: false
  tasks:
    - name: Set DNS servers
      win_dns_client:
        adapter_names: "*"
        ipv4_addresses:
          - 172.16.1.50
          - 172.16.3.10
    - name: Reboot to Force DNS
      win_reboot:
