- hosts: 127.0.0.1
  tasks:
    - name: Wait for DC1_biz Provisioning and boot to complete
      wait_for:
        host: 172.16.2.5
        port: 5985
        delay: 30
        sleep: 30
        timeout: 300
- hosts: dc1_biz
  gather_facts: true
  tasks:
    - name: Set DNS servers
      win_dns_client:
        adapter_names: "*"
        ipv4_addresses:
          - 172.16.1.50
          - 172.16.1.51
    - name: Create Temp folder
      win_file:
        path: c:\temp
        state: directory
    - name: Copy DCPROMO unattend file
      win_copy:
        src: ../files/dc1_biz.unattend.txt
        dest: c:\temp
    - name: Force Copy
      win_shell: copy-item source c:\temp\dc1_biz.unattend.txt
    - name: Install GPMC
      win_feature:
        name: GPMC
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install Backup-Features
      win_feature:
        name: Backup-Features
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install Backup
      win_feature:
        name: Backup
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install Backup-Tools
      win_feature:
        name: Backup-Tools
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install DNS and WINS
      win_feature:
        name: DNS,WINS-Server
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: Install AS-Net-Framework
      win_feature:
        name: AS-NET-Framework
        state: present
    - name: Install Domain Services
      win_feature:
        name: AD-Domain-Services,ADDS-Domain-Controller
        state: present
        restart: true
    - name: Run DCPROMO to create domain
      win_command: dcpromo.exe /unattend:c:\temp\dc1_biz.unattend.txt
      register: dc1_promo_result
      failed_when:
        - dc1_promo_result.rc >= 11
- hosts: 127.0.0.1
  tasks:
    - name: Wait for DC1_biz reboot to finish
      wait_for:
        host: 172.16.2.5
        port: 5985
        delay: 60
        sleep: 60
        timeout: 600
- hosts: dc1_biz
  vars:
    ansible_user: mercy\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: false
  tasks:
    - name: Testing Connectivity to DC1_Biz
      win_ping:
    - name: Write checkpoint file if domain creation was a success
      win_file:
        path: c:\temp\dc.success
        state: touch
        when: dc1_promo_result.rc <= 10
    - name: Set DNS servers
      win_dns_client:
        adapter_names: "*"
        ipv4_addresses:
          - 172.16.1.50
          - 172.16.2.5
