- hosts: 127.0.0.1
  tasks:
    - name: Wait for DC1_corp Provisioning and boot to complete
      wait_for:
        host: 172.16.1.50
        port: 5985
        delay: 15
        sleep: 15
        timeout: 300
- hosts: dc1_corp
  gather_facts: true
  tasks:
    - name: Check for DCPROMO prior execution
      win_stat:
        path: c:\temp\dc.success
        register: dc_stat
    - name: Create Temp folder
      win_file:
        path: c:\temp
        state: directory
        when: dc_stat.stat.exists == False
    - name: Copy DCPROMO unattend file
      win_copy:
        src: ../files/dc1.unattend.txt
        dest: c:\temp
        retries: 3
        when: dc_stat.stat.exists == False
    - name: Install GPMC
      win_feature:
        name: GPMC
        state: present
        include_sub_features: true
        include_management_tools: true
        when: dc_stat.stat.exists == False
    - name: Install Backup-Features
      win_feature:
        name: Backup-Features
        state: present
        include_sub_features: true
        include_management_tools: true
        when: dc_stat.stat.exists == False
    - name: Install Backup
      win_feature:
        name: Backup
        state: present
        include_sub_features: true
        include_management_tools: true
        when: dc_stat.stat.exists == False
    - name: Install Backup-Tools
      win_feature:
        name: Backup-Tools
        state: present
        include_sub_features: true
        include_management_tools: true
        when: dc_stat.stat.exists == False
    - name: Install DNS and WINS
      win_feature:
        name: DNS,WINS-Server
        state: present
        include_sub_features: true
        include_management_tools: true
        when: dc_stat.stat.exists == False
    - name: Install AS-Net-Framework
      win_feature:
        name: AS-NET-Framework
        state: present
        when: dc_stat.stat.exists == False
    - name: Install Domain Services
      win_feature:
        name: AD-Domain-Services,ADDS-Domain-Controller
        state: present
        restart: true
        when: dc_stat.stat.exists == False
    - name: Run DCPROMO to create domain
      win_command: dcpromo.exe /unattend:c:\temp\dc1.unattend.txt
      register: dc1_promo_result
      when: dc_stat.stat.exists == False
      failed_when:
        - dc1_promo_result.rc >= 11
- hosts: 127.0.0.1
  tasks:
    - name: Wait for DC1_corp reboot to finish
      wait_for:
        host: 172.16.1.50
        port: 5985
        delay: 30
        sleep: 30
        timeout: 600
- hosts: dc1_corp
  gather_facts: false
  tasks:
    - name: Testing Connectivity to DC1
      win_ping:
    - name: Write checkpoint file if domain creation was a success
      win_file:
        path: c:\temp\dc.success
        state: touch
        when: dc1_promo_result.rc <= 10
