- hosts: 127.0.0.1
  tasks:
    - name: Wait for DC1_corp Provisioning and boot to complete
      wait_for:
        host: 172.16.1.50
        port: 5985
        delay: 60
        sleep: 15
- hosts: dc1_corp
  vars:
    ansible_user: mercy\vagrant
    ansible_password: "vagrant"
  gather_facts: true
  tasks:
