- hosts: exchange
  gather_facts: true
  tasks:
    - name: Set DNS
      win_dns_client:
        adapter_names: "*"
        ipv4_addresses:
          - 172.16.1.50
          - 172.16.1.51
    - name: Join domain
      win_domain_membership:
        state: domain
        hostname: exchange
        dns_domain_name: mercytechhealthcare.local
        domain_admin_user: administrator@mercytechhealthcare.local
        domain_admin_password: Sh73PJ8eK4n4wH3a6hPQTJZq
      register: domain_state
    - name: chocolatey
      win_chocolatey:
        name: powershell
        state: present
