- hosts: exchange
  gather_facts: true
  tasks:
    - name: Set DNS
      win_dns_client:
        adapter_names: "*"
        ipv4_addresses:
          - 172.16.1.50
          - 172.16.1.51
    - name: Join domain
      win_domain_membership:
        state: domain
        hostname: exchange
        dns_domain_name: mercytechhealthcare.local
        domain_admin_user: administrator@mercytechhealthcare.local
        domain_admin_password: Sh73PJ8eK4n4wH3a6hPQTJZq
      register: domain_state
    - name: Create Exchange Temp directory
      win_file:
        path: c:\exchangeinstall
        state: directory
    - name: Check for file
      win_stat:
        path: c:\exchangeinstall\exchange2013.Zip
      register: zip_stat
    - name: Copy Exchange Zip
      win_copy:
        src: ../files/exchange2013.zip
        dest: c:\exchangeinstall\exchange2013.Zip
        when: zip_stat.stat.size > 0
    - name: Unzip
      win_unzip:
        src: c:\exchangeinstall\exchange2013.Zip
        dest: c:\exchangeinstall\disk
        rm: yes
    - name: Setup Share
      win_share:
        name: disk
        path: c:\exchangeinstall\disk
        full: Everyone
    - name: Copy script
      win_copy:
        src: ../files/Install-Exchange15.ps1
        dest: c:\exchangeinstall\Install-Exchange15.ps1
    - name: Unblock
      win_shell: Unblock-File c:\exchangeinstall\Install-Exchange15.ps1
