- hosts: exchange
  vars:
    ansible_user: administrator@mercytechhealthcare.local
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: true
  tasks:
    - name: Install .net 461
      win_shell: c:\exchangeinstall\NDP461-KB3102436-x86-x64-AllOS-ENU.exe /q /norestart
    - name: Install KB3146715
      win_shell: Start-Process -FilePath c:\windows\system32\wusa.exe -ArgumentList "c:\exchangeinstall\Windows8.1-KB3146715-x64.msu /f /quiet /norestart" -NoNewWindow -PassThru -Wait
    - name: Install UCMA Runtime
      win_shell: c:\exchangeinstall\ucmaruntimesetup.exe /passive /norestart
    - name: Reboot before Installing Exchange
      win_reboot:
