- hosts: exchange
  gather_facts: true
  tasks:
    - name: Create Exchange Temp directory
      win_file:
        path: c:\exchangeinstall
        state: directory
    - name: Check for file
      win_stat:
        path: c:\exchangeinstall\exchange2013.Zip
      register: zip_stat
    - name: Copy Exchange Zip
      win_copy:
        src: ../files/exchange2013.zip
        dest: c:\exchangeinstall\exchange2013.Zip
        when: zip_stat.stat.size > 0
    - name: Unzip
      win_unzip:
        src: c:\exchangeinstall\exchange2013.Zip
        dest: c:\exchangeinstall\disk
        rm: yes
    - name: Check for file for Mailboxes
      win_stat:
        path: c:\exchangeinstall\mailboxes.zip
      register: zip_stat
    - name: Copy Exchange Mailboxes
      win_copy:
        src: ../files/mailboxes.zip
        dest: c:\exchangeinstall\mailboxes.zip
        when: zip_stat.stat.size > 0
    - name: Unzip Exchange Mailboxes
      win_unzip:
        src: c:\exchangeinstall\mailboxes.Zip
        dest: c:\exchangeinstall\disk\mailboxes
        rm: yes
    - name: Check for file for Exchange Prereqs
      win_stat:
        path: c:\exchangeinstall\exchangeinstall.zip
      register: zip_stat
    - name: Copy Exchange Prereqs Zip
      win_copy:
        src: ../files/exchangeinstall.zip
        dest: c:\exchangeinstall\exchangeinstall.zip
        when: zip_stat.stat.size > 0

    - name: Unzip Exchange Prereqs
      win_unzip:
        src: c:\exchangeinstall\exchangeinstall.Zip
        dest: c:\exchangeinstall\
        rm: yes
    - name: Setup Share
      win_share:
        name: disk
        path: c:\exchangeinstall\disk
        full: Everyone
    - name: Copy Driver script
      win_copy:
        src: ../files/exchangedriver.ps1
        dest: c:\exchangeinstall\exchangedriver.ps1
    - name: Unblock Driver
      win_shell: Unblock-File c:\exchangeinstall\exchangedriver.ps1
    - name: Copy Exchange Install script
      win_copy:
        src: ../files/Install-Exchange15.ps1
        dest: c:\exchangeinstall\Install-Exchange15.ps1
    - name: Unblock
      win_shell: Unblock-File c:\exchangeinstall\Install-Exchange15.ps1
    - name: Reboot System
      win_reboot:
    - name: Install KB2919442
      win_shell: c:\exchangeinstall\Windows8.1-KB29194420x64.msu /quiet /norestart
    - name: Install KB2919355
      win_shell: c:\exchangeinstall\Windows8.1-KB2919355-x64.msu /quiet /norestart
    - name: Install .net 461
      win_shell: c:\exchangeinstall\NDP461-KB3102436-x86-x64-AllOS-ENU.exe /q /norestart
    - name: Install KB3146715
      win_shell: c:\exchangeinstall\Windows8.1-KB3146715-x64.msu /quiet /norestart
    - name: Install KB3041832 for High CPU usage
      win_shell: c:\exchangeinstall\482449_intl_x64_zip.exe /quiet /norestart
    - name: Reboot before Installing Exchange
      win_reboot:
    - name: Prepare AD
      win_shell: c:\exchangeinstall\disk\setup.exe /PrepareAD /OrganizationName=`Mercy Tech Healthcare` /IAcceptExchangeServerLicenseTerms
    - name: Prepare Install Exchange
      win_shell: c:\exchangeinstall\disk\setup.exe /IAcceptExchangeServerLicenseTerms /InstallWindowsComponents /roles:Mailbox,ClientAccess /DoNotStartTransport
    - name: Set Transport
      win_shell: Set-Service MSExchangeTransport -StartupType Manual
    - name: Set FrontEndTransport
      win_shell: Set-Service MSExchangeFrontEndTransport -StartupType Manual
    - name: Install Filter Pack
      win_shell: c:\exchangeinstall\FilterPack64bit.exe /passive /norestart
    - name: Install FilterPack SP1
      win_shell: c:\exchangeinstall\filterpack2010sp1-kb2460041-x64-fullfile-en-us.exe /passive /norestart
    - name: Reboot again
      win_reboot:
