- hosts: files
  gather_facts: true
  tasks:
    - name: Create Share structure
      win_file:
        path: c:\shares
        state: directory
    - win_file:
        path: c:\shares\IT
        state: directory
    - win_file:
        path: c:\shares\HR
        state: directory
    - win_file:
        path: c:\shares\Finance
        state: directory
    - win_file:
        path: c:\shares\IT\exchange
        state: directory
    - win_file:
        path: c:\shares\executive
        state: directory
    - name: Add IT Share
      win_share:
        name: IT
        path: c:\shares\IT
        list: 'no'
        full: Everyone
    - name: Add Finance Share
      win_share:
        name: Finance
        path: c:\shares\Finance
        list: 'yes'
        full: Everyone
