- hosts: windows
  gather_facts: false
  tasks:
    - name: Set Disable Firewalls
      win_firewall:
        state: disabled
        profiles:
          - Domain
          - Public
          - Private
