- hosts: firewall
  remote_user: root
  connection: ssh
  tasks:
    - name: Set IP Forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
