- hosts: ImpactStations
- vars:
    ansible_user: vagrant
    ansible_password: vagrant
- tasks:
    - name: Create temp folder
      win_file:
        path: c:\temp
        state: directory
    - name: Sync Impact files to folder
      win_copy:
        src: ../files/impact/
        dest: c:\temp
        retries: 5
    - name: Create local CTF user
      win_user:
        name: CTF
        password: CTF
        state: present
        password_never_expires: yes
        groups_action: add
        groups:
          - "Remote Desktop Users"
    - name: Set Auto Login for CTF username
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: DefaultUserName
        value: CTF
        type: string
        state: present
    - name: Set Auto Login password for CTF
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: DefaultPassword
        value: CTF
        type: string
        state: present
    - name: Set AutoAdminLogin
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: AutoAdminLogon
        value: 1
        type: string
        state: present
    - name: Reboot
      win_reboot:
