- hosts: ImpactStations
  vars:
    ansible_user: vagrant
    ansible_password: vagrant
  tasks:
    - name: Create local CTF user
      win_user:
        name: CTF
        password: CTF
        state: present
        password_never_expires: yes
        groups_action: add
        groups:
          - "Remote Desktop Users"
    - name: Set Auto Login for CTF username
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: DefaultUserName
        value: CTF
        type: string
        state: present
    - name: Set Auto Login password for CTF
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: DefaultPassword
        value: ctf
        type: string
        state: present
    - name: Set AutoAdminLogin
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: AutoAdminLogon
        value: 1
        type: string
        state: present
    - name: Reboot
      win_reboot:
    - name: install PSExec
      win_chocolatey:
        name: psexec
        state: latest
    - name: Install Impact
      win_psexec:
        command: c:\impact\impact\UnattendedInstall.exe -v v:PASSPHRASE:U6BPT8-P6NXCK-6ZXDBN-YWSHAD-UBS59Y -i c:\impact\CORE_IMPACT-2017_R1.exe -x c:\impact\impact.xml
        interactive: yes
    - name: Install Third Party Tools
      win_psexec:
        command: c:\impact\impact\UnattendedInstall.exe -v v:PASSPHRASE:U6BPT8-P6NXCK-6ZXDBN-YWSHAD-UBS59Y -i c:\impact\CORE_IMPACT_3rdparty.exe -x c:\impact\impact-3rd-party.xml
        interactive: yes
    - name: Activate Impact
      win_psexec:
        command: c:\impact\impact\UnattendedInstall.exe -v v:PASSPHRASE:U6BPT8-P6NXCK-6ZXDBN-YWSHAD-UBS59Y -i impact.exe -x c:\impact\impact-launcher.xml
        interactive: yes
