- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Wait for WinRM to come up
      wait_for:
        host: 10.0.0.7
        port: 5985 
        delay: 5 
        timeout: 600
- hosts: 10.0.0.7
  gather_facts: true
  tasks:
    - name: Wait for VMware tools to become available by UUID
      vmware_guest_tools_wait:
        hostname: 10.0.0.10
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        name: CTF-MGMT-DHCP
        folder: Management
      delegate_to: localhost
      register: facts
    - name: Wait for the system to come up
      wait_for_connection:
        delay: 30
        sleep: 15
    - name: Install DNS Role
      win_shell: Install-WindowsFeature -Name 'DNS' –IncludeManagementTools
    - name: Create DNS zone
      win_shell: Add-DnsServerPrimaryZone -Name "ctf.local" -ZoneFile "ctf.local.dns"
    - name: Create DNS Zone
      win_shell: Add-DnsServerPrimaryZone -NetworkID 10.1.0.0/24 -ZoneFile "0.1.10.in-addr.arpa.dns"
    - name: Add Scoreboard
      win_shell: Add-DnsServerResourceRecordA -Name "scoreboard" -ZoneName "ctf.local" -AllowUpdateAny -IPv4Address "192.168.50.5" -TimeToLive 01:00:00
    - name: Add ansible
      win_shell: Add-DnsServerResourceRecordA -Name "ansible" -ZoneName "ctf.local" -AllowUpdateAny -IPv4Address "10.1.0.10" -TimeToLive 01:00:00
    - name: Add Router
      win_shell: Add-DnsServerResourceRecordA -Name "router" -ZoneName "ctf.local" -AllowUpdateAny -IPv4Address "10.1.0.1" -TimeToLive 01:00:00
    - name: Add AP
      win_shell: Add-DnsServerResourceRecordA -Name "ap" -ZoneName "ctf.local" -AllowUpdateAny -IPv4Address "10.1.0.254" -TimeToLive 01:00:00
    - name: Add switch
      win_shell: Add-DnsServerResourceRecordA -Name "switch" -ZoneName "ctf.local" -AllowUpdateAny -IPv4Address "10.1.0.253" -TimeToLive 01:00:00
    - name: Add vcenter
      win_shell: Add-DnsServerResourceRecordA -Name "vcenter" -ZoneName "ctf.local" -AllowUpdateAny -IPv4Address "10.1.0.199" -TimeToLive 01:00:00
    - name: Add host1
      win_shell: Add-DnsServerResourceRecordA -Name "host1" -ZoneName "ctf.local" -AllowUpdateAny -IPv4Address "10.1.200" -TimeToLive 01:00:00
    - name: Add host2
      win_shell: Add-DnsServerResourceRecordA -Name "host2" -ZoneName "ctf.local" -AllowUpdateAny -IPv4Address "10.1.0.201" -TimeToLive 01:00:00

    - name: Install DHCP Role
      win_shell: Install-WindowsFeature -Name 'DHCP' –IncludeManagementTools
    - name: Add firewall groups
      win_shell: cmd.exe /c "netsh dhcp add securitygroups"
    - name: Restart dhcp
      win_shell: Restart-service dhcpserver
    - name: Trick Server manager
      win_shell: Set-ItemProperty –Path registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ServerManager\Roles\12 –Name ConfigurationState –Value 2
    - name: Setup Scope
      win_shell: Add-DhcpServerV4Scope -Name ManagementDHCP -StartRange 10.1.0.20 -EndRange 10.1.0.100 -SubnetMask 255.255.255.0 -State Active
    - name: Setup Options
      win_shell: Set-DhcpServerV4OptionValue -DnsDomain ctf.local -Router 10.1.0.1 -DnsServer 10.1.0.7
    - name: Set scope Options
      win_shell: Set-DhcpServerv4Scope -ScopeId 10.1.0.0 -LeaseDuration 1.00:00:00
