- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Provision Impact01 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-01
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.101
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.101
          netmask: 255.255.255.0
      customization:
        hostname: CTF01
        password: ctf
  - name: Provision Impact02 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-02
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.102
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.102
          netmask: 255.255.255.0
      customization:
        hostname: CTF02
        password: ctf
  - name: Provision Impact03 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-03
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.103
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.103
          netmask: 255.255.255.0
      customization:
        hostname: CTF03
        password: ctf
  - name: Provision Impact04 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-04
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.104
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.104
          netmask: 255.255.255.0
      customization:
        hostname: CTF04
        password: ctf
  - name: Provision Impact05 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-05
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.105
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.105
          netmask: 255.255.255.0
      customization:
        hostname: CTF05
        password: ctf
  - name: Provision Impact06 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-06
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.106
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.106
          netmask: 255.255.255.0
      customization:
        hostname: CTF06
        password: ctf
  - name: Provision Impact07 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-07
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.107
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.107
          netmask: 255.255.255.0
      customization:
        hostname: CTF07
        password: ctf
  - name: Provision Impact08 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-08
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.108
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.108
          netmask: 255.255.255.0
      customization:
        hostname: CTF08
        password: ctf
  - name: Provision Impact09 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-09
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.109
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.109
          netmask: 255.255.255.0
      customization:
        hostname: CTF09
        password: ctf
  - name: Provision Impact10 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-10
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.110
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.110
          netmask: 255.255.255.0
      customization:
        hostname: CTF10
        password: ctf
  - name: Provision Impact11 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-11
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.111
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.111
          netmask: 255.255.255.0
      customization:
        hostname: CTF11
        password: ctf
  - name: Provision Impact12 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-12
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.112
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.112
          netmask: 255.255.255.0
      customization:
        hostname: CTF12
        password: ctf
  - name: Provision Impact13 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-13
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.113
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.113
          netmask: 255.255.255.0
      customization:
        hostname: CTF13
        password: ctf
  - name: Provision Impact14 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-14
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.114
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.114
          netmask: 255.255.255.0
      customization:
        hostname: CTF14
        password: ctf
  - name: Provision Impact15 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-15
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.115
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.115
          netmask: 255.255.255.0
      customization:
        hostname: CTF15
        password: ctf
  - name: Provision Impact16 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-16
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.116
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.116
          netmask: 255.255.255.0
      customization:
        hostname: CTF16
        password: ctf
  - name: Provision Impact17 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-17
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.117
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.117
          netmask: 255.255.255.0
      customization:
        hostname: CTF17
        password: ctf
  - name: Provision Impact18 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-18
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.118
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.118
          netmask: 255.255.255.0
      customization:
        hostname: CTF18
        password: ctf
  - name: Provision Impact19 from template
    vmware_guest:
      hostname: 10.0.0.10
      username: ansible@vsphere.local
      password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
      validate_certs: no
      datacenter: Datacenter
      folder: Attackers
      name: CTF-IMPACT-19
      template: ctf-player
      state: poweredon
      esxi_hostname: 10.0.0.11
      networks:
        - name: CTF-CorpNet
          ip: 172.16.5.119
          netmask: 255.255.255.0
          gateway: 172.16.5.1
          domain: bank.local
          dns_servers:
            - 172.16.5.5
            - 8.8.8.8
        - name: CTF-RedTeamNet
          ip: 192.168.50.119
          netmask: 255.255.255.0
      customization:
        hostname: CTF19
        password: ctf
