    - name: Provision Impact01 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-01
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.101
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.101
            netmask: 255.255.254.0
        customization:
          hostname: CTF01
          password: CTF
    - name: Provision Impact02 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-02
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.102
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.102
            netmask: 255.255.254.0
        customization:
          hostname: CTF02
          password: CTF
    - name: Provision Impact03 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-03
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.103
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.103
            netmask: 255.255.254.0
        customization:
          hostname: CTF03
          password: CTF
    - name: Provision Impact04 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-04
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.104
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.104
            netmask: 255.255.254.0
        customization:
          hostname: CTF04
          password: CTF
    - name: Provision Impact05 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-05
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.105
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.105
            netmask: 255.255.254.0
        customization:
          hostname: CTF05
          password: CTF
    - name: Provision Impact06 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-06
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.106
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.106
            netmask: 255.255.254.0
        customization:
          hostname: CTF06
          password: CTF
    - name: Provision Impact07 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-07
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.107
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.107
            netmask: 255.255.254.0
        customization:
          hostname: CTF07
          password: CTF
    - name: Provision Impact08 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-08
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.108
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.108
            netmask: 255.255.254.0
        customization:
          hostname: CTF08
          password: CTF
    - name: Provision Impact09 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-09
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.109
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.109
            netmask: 255.255.254.0
        customization:
          hostname: CTF09
          password: CTF
    - name: Provision Impact10 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-10
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.110
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.110
            netmask: 255.255.254.0
        customization:
          hostname: CTF10
          password: CTF
    - name: Provision Impact11 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-11
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.111
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.111
            netmask: 255.255.254.0
        customization:
          hostname: CTF11
          password: CTF
    - name: Provision Impact12 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-12
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.112
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.112
            netmask: 255.255.254.0
        customization:
          hostname: CTF12
          password: CTF
    - name: Provision Impact13 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-13
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.113
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.113
            netmask: 255.255.254.0
        customization:
          hostname: CTF13
          password: CTF
    - name: Provision Impact14 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-14
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.114
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.114
            netmask: 255.255.254.0
        customization:
          hostname: CTF14
          password: CTF
    - name: Provision Impact15 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-15
        template: impact-win7x64ent
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.115
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.3.10
              - 172.16.3.11
          - name: CTF-RedTeamNet
            ip: 192.168.50.115
            netmask: 255.255.254.0
        customization:
          hostname: CTF15
          password: CTF
