- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Nuke CTF Firewall
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-Perimeter-FW
        force: yes
        state: poweredoff
    - name: Nuke CTF Firewall
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        esxi_hostname: 10.1.0.200
        name: CTF-Perimeter-FW
        force: yes
        state: absent
    - name: Nuke Linux Test Box
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-LinuxTest
        state: absent
        force: yes
    - name: Nuke Biz Domain DC1
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-DC1-BIZ
        state: absent
        force: yes
    - name: Nuke Corp Domain DC1
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-DC1-CORP
        state: absent
        force: yes
    - name: Nuke Biz Domain DC2
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-DC2-BIZ
        state: absent
        force: yes
    - name: Nuke Corp Domain DC2
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-DC2-CORP
        state: absent
        force: yes
    - name: Nuke Corp exchange
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-EXCHANGE
        state: absent
        force: yes
    - name: Nuke Corp files
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-FILES-CORP
        state: absent
        force: yes
    - name: Nuke RSmith
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-RSmith
        state: absent
        force: yes
    - name: Nuke DMeeks
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-DMeeks
        state: absent
        force: yes
    - name: Nuke JWilson
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-JWilson
        state: absent
        force: yes
    - name: Nuke SBarber
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-SBarber
        state: absent
        force: yes
    - name: Nuke CWebb
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-CWebb
        state: absent
        force: yes
    - name: Nuke BStone
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-BStone
        state: absent
        force: yes
    - name: Nuke GWillis
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-GWillis
        state: absent
        force: yes
    - name: Nuke KEdge
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-KEdge
        state: absent
        force: yes
    - name: Nuke RTaylor
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-RTaylor
        state: absent
        force: yes
    - name: Nuke SStrange
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-SStrange
        state: absent
        force: yes
    - name: Nuke BHoward
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-BHoward
        state: absent
        force: yes
