- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Nuke CTF Firewall 
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        guest: CTF-Perimeter-FW
        force: yes
        state: absent 
    - name: Nuke Linux Test Box
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        guest: CTF-LinuxTest
        state: absent
        force: yes
    - name: Nuke Biz Domain DC1
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        guest: CTF-DC1-BIZ
        state: absent
        force: yes
    - name: Nuke Corp Domain DC1
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        guest: CTF-DC1-CORP
        state: absent
        force: yes     
    - name: Nuke Biz Domain DC2
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        guest: CTF-DC2-BIZ
        state: absent
        force: yes
    - name: Nuke Corp Domain DC2
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        guest: CTF-DC2-CORP
        state: absent
        force: yes
   