- hosts: 127.0.0.1
  tasks:
    - name: Wait for Red_DHCP Provisioning and boot to complete
      wait_for:
        host: 192.168.50.2
        port: 5985
        delay: 15
        sleep: 15
        timeout: 300
- hosts: 192.168.50.2
  gather_facts: true
  tasks:
    - name: Install DNS Role
      win_shell: Install-WindowsFeature -Name 'DNS' –IncludeManagementTools
    - name: Create DNS zone
      win_shell: Add-DnsServerPrimaryZone -Name "ctf.local" -ZoneFile "ctf.local.dns"
    - name: Create DNS Zone
      win_shell: Add-DnsServerPrimaryZone -NetworkID 192.168.50.0/22 -ZoneFile "50.168.192.in-addr.arpa.dns"
    - name: create temp folder
      win_file:
        path: c:\temp
        state: directory
    - name: Copy DNS Script
      win_copy:
        src: ../files/config_participant_dns.ps1
        dest: c:\temp\config_participant_dns.ps1
    - name: Unblock script:
      win_shell: Unblock-File c:\temp\config_participant_dns.ps1
    - name: Run script to add dns records
      win_shell: c:\temp\config_participant_dns.ps1
    - name: Install DHCP Role
      win_shell: Install-WindowsFeature -Name 'DHCP' –IncludeManagementTools
    - name: Add firewall groups
      win_shell: cmd.exe /c "netsh dhcp add securitygroups"
    - name: Restart dhcp
      win_shell: Restart-service dhcpserver
    - name: Trick Server manager
      win_shell: Set-ItemProperty –Path registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ServerManager\Roles\12 –Name ConfigurationState –Value 2
    - name: Setup Scope
      win_shell: Add-DhcpServerV4Scope -Name RedTeamScope -StartRange 192.168.52.1 -EndRange 192.168.52.254 -SubnetMask 255.255.252.0 -State Active
    - name: Setup Options
      win_shell: Set-DhcpServerV4OptionValue -DnsDomain ctf.local -Router 192.168.50.1 -DnsServer 192.168.50.2
    - name: Set scope Options
      win_shell: Set-DhcpServerv4Scope -ScopeId 192.168.50.0 -LeaseDuration 1.00:00:00
