- hosts: 172.16.1.75
  vars:
    ansible_user: mercy\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: true
  tasks:
    - name: Set Autologin RSmith
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoAdminLogon /t REG_SZ /d 1"
    - name: Set Autologin RSmith
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultUserName /t REG_SZ /d robert.smith"
    - name: Set Autologin RSmith
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultDomainName /t REG_SZ /d mercy"
    - name: Set Autologin RSmith
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultPassword /t REG_SZ /d IAmGod1"
    - name: Set Autologin RSmith
      win_shell: "reg delete \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoLogonCount"
      ignore_errors: yes
    - name: Set Autologin RSmith
      win_reboot:
- hosts: 172.16.1.76
  vars:
    ansible_user: mercy\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: true
  tasks:
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoAdminLogon /t REG_SZ /d 1"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultUserName /t REG_SZ /d donna.meeks"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultDomainName /t REG_SZ /d mercy"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultPassword /t REG_SZ /d Nana60"
    - name: Set Autologin DMeeks
      win_shell: "reg delete \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoLogonCount"
      ignore_errors: yes
    - name: Set Autologin DMeeks
      win_reboot:
- hosts: 172.16.1.77
  vars:
    ansible_user: mercy\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: true
  tasks:
    - name: Set Autologin JWilson
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoAdminLogon /t REG_SZ /d 1"
    - name: Set Autologin JWilson
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultUserName /t REG_SZ /d jeremy.wilson"
    - name: Set Autologin JWilson
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultDomainName /t REG_SZ /d mercy"
    - name: Set Autologin JWilson
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultPassword /t REG_SZ /d 1111111"
    - name: Set Autologin JWilson
      win_shell: "reg delete \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoLogonCount"
      ignore_errors: yes
    - name: Set Autologin JWilson
      win_reboot:
- hosts: 172.16.1.78
  vars:
    ansible_user: mercy\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: true
  tasks:
    - name: Set Autologin SBarber
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoAdminLogon /t REG_SZ /d 1"
    - name: Set Autologin SBarber
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultUserName /t REG_SZ /d shirley.barber"
    - name: Set Autologin SBarber
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultDomainName /t REG_SZ /d mercy"
    - name: Set Autologin SBarber
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultPassword /t REG_SZ /d password03"
    - name: Set Autologin SBarber
      win_shell: "reg delete \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoLogonCount"
      ignore_errors: yes
    - name: Set Autologin SBarber
      win_reboot:
- hosts: 172.16.1.79
  vars:
    ansible_user: mercy\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: true
  tasks:
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoAdminLogon /t REG_SZ /d 1"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultUserName /t REG_SZ /d connie.webb"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultDomainName /t REG_SZ /d mercy"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultPassword /t REG_SZ /d ih8hippa"
    - name: Set Autologin DMeeks
      win_shell: "reg delete \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoLogonCount"
      ignore_errors: yes
    - name: Set Autologin DMeeks
      win_reboot:
- hosts: 172.16.1.80
  vars:
    ansible_user: mercy\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: true
  tasks:
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoAdminLogon /t REG_SZ /d 1"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultUserName /t REG_SZ /d barry.stone"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultDomainName /t REG_SZ /d mercy"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultPassword /t REG_SZ /d Drachmas72"
    - name: Set Autologin DMeeks
      win_shell: "reg delete \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoLogonCount"
      ignore_errors: yes
    - name: Set Autologin DMeeks
      win_reboot:
- hosts: 172.16.1.81
  vars:
    ansible_user: mercy\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: true
  tasks:
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoAdminLogon /t REG_SZ /d 1"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultUserName /t REG_SZ /d gail.willis"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultDomainName /t REG_SZ /d mercy"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultPassword /t REG_SZ /d hoppin18"
    - name: Set Autologin DMeeks
      win_shell: "reg delete \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoLogonCount"
      ignore_errors: yes
    - name: Set Autologin DMeeks
      win_reboot:
- hosts: 172.16.1.82
  vars:
    ansible_user: mercy\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: true
  tasks:
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoAdminLogon /t REG_SZ /d 1"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultUserName /t REG_SZ /d kristy.edge"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultDomainName /t REG_SZ /d mercy"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultPassword /t REG_SZ /d Mbdays85"
    - name: Set Autologin DMeeks
      win_shell: "reg delete \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoLogonCount"
      ignore_errors: yes
    - name: Set Autologin DMeeks
      win_reboot:
- hosts: 172.16.1.83
  vars:
    ansible_user: mercy\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: true
  tasks:
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoAdminLogon /t REG_SZ /d 1"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultUserName /t REG_SZ /d renee.taylor"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultDomainName /t REG_SZ /d mercy"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultPassword /t REG_SZ /d headb75"
    - name: Set Autologin DMeeks
      win_shell: "reg delete \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoLogonCount"
      ignore_errors: yes
    - name: Set Autologin DMeeks
      win_reboot:
- hosts: 172.16.1.84
  vars:
    ansible_user: mercy\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: true
  tasks:
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoAdminLogon /t REG_SZ /d 1"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultUserName /t REG_SZ /d stephen.strange"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultDomainName /t REG_SZ /d mercy"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultPassword /t REG_SZ /d Donna92"
    - name: Set Autologin DMeeks
      win_shell: "reg delete \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoLogonCount"
      ignore_errors: yes
    - name: Set Autologin DMeeks
      win_reboot:
- hosts: 172.16.1.85
  vars:
    ansible_user: mercy\administrator
    ansible_password: Sh73PJ8eK4n4wH3a6hPQTJZq
  gather_facts: true
  tasks:
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoAdminLogon /t REG_SZ /d 1"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultUserName /t REG_SZ /d bob.howard"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultDomainName /t REG_SZ /d mercy"
    - name: Set Autologin DMeeks
      win_shell: "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v DefaultPassword /t REG_SZ /d tentacles2004"
    - name: Set Autologin DMeeks
      win_shell: "reg delete \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /f /v AutoLogonCount"
      ignore_errors: yes
    - name: Set Autologin DMeeks
      win_reboot:
