- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Provision CTF00 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        name: CTF-IMPACT-00
        template: ctf-impact
        state: poweredon
        esxi_hostname: 10.1.0.201
        networks:
          - name: CTF-ClinicalNet
            ip: 172.16.3.100
            netmask: 255.255.255.0
            gateway: 172.16.3.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.1.50
              - 172.16.1.51
          - name: CTF-RedTeamNet
            ip: 192.168.50.100
            netmask: 255.255.254.0
        customization:
          hostname: CTF00
          password: CTF
