- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Provision CTF Firewall from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        esxi_hostname: 10.1.0.200
        name: CTF-Perimeter-FW
        template: ctf-centos66
        state: poweredon
        networks:
          - name: CTF-RouterLink
            ip: 172.16.201.2
            netmask: 255.255.255.252
            gateway: 172.16.201.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 8.8.8.8
              - 4.2.2.2
          - name: CTF-DMZNet
            ip: 172.16.5.1
            netmask: 255.255.255.0
          - name: CTF-CorpNet
            ip: 172.16.1.1
            netmask: 255.255.255.0
          - name: CTF-BizNet
            ip: 172.16.2.1
            netmask: 255.255.255.0
          - name: CTF-ClinicalNet
            ip: 172.16.3.1
            netmask: 255.255.255.0
    - name: Wait for Firewall Provisioning and boot to complete
      wait_for:
        host: 172.16.201.2
        port: 22
        delay: 60
        sleep: 15
