- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Provision Corp Domain exchange from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-EXCHANGE
        template: ctf-win2012r2-standard
        state: poweredon
        networks:
          - name: CTF-CorpNet
            ip: 172.16.1.18
            netmask: 255.255.255.0
            gateway: 172.16.1.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 172.16.1.50
              - 172.16.1.51
        customization:
          hostname: exchange
          password: Sh73PJ8eK4n4wH3a6hPQTJZq
          dns_servers:
            - 8.8.8.8
            - 4.2.2.2
