- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Provision Secure Network Primary DC
      vmware_guest:
        hostname: 10.0.0.10
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        folder: Targets
        esxi_hostname: 10.0.0.12
        name: CTF-DC1-SECURE
        template: ctf-win2008r2-standard-12
        state: poweredon
        wait_for_ip_address: yes
        networks:
          - name: CTF-SecureNet
            ip: 172.16.1.5
            netmask: 255.255.255.0
            gateway: 172.16.1.1
            domain: bank.local
            dns_servers:
              - 8.8.8.8
              - 4.2.2.2
        customization:
          hostname: dc1
          password: Sh73PJ8eK4n4wH3a6hPQTJZq
          dns_servers:
            - 8.8.8.8
            - 4.2.2.2
    - name: Provision Secure Network Secondary DC
      vmware_guest:
        hostname: 10.0.0.10
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        folder: Targets
        esxi_hostname: 10.0.0.12
        name: CTF-DC2-SECURE
        template: ctf-win2008r2-standard-12
        state: poweredon
        wait_for_ip_address: yes
        networks:
          - name: CTF-SecureNet
            ip: 172.16.1.6
            netmask: 255.255.255.0
            gateway: 172.16.1.1
            domain: bank.local
            dns_servers:
              - 8.8.8.8
              - 4.2.2.2
        customization:
          hostname: dc2
          password: Sh73PJ8eK4n4wH3a6hPQTJZq
          dns_servers:
            - 8.8.8.8
            - 4.2.2.2
    - name: Provision Secure Network Database Server
      vmware_guest:
        hostname: 10.0.0.10
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        folder: Targets
        esxi_hostname: 10.0.0.12
        name: CTF-DB-SECURE
        template: ubuntu1604-12
        state: poweredon
        wait_for_ip_address: yes
        networks:
          - name: CTF-SecureNet
            ip: 172.16.1.10
            netmask: 255.255.255.0
            gateway: 172.16.1.1
            domain: bank.local
            dns_servers:
              - 8.8.8.8
              - 4.2.2.2
        customization:
          hostname: db
          password: Sh73PJ8eK4n4wH3a6hPQTJZq
          dns_servers:
            - 8.8.8.8
            - 4.2.2.2
    - name: Provision Secure Network Swift Server
      vmware_guest:
        hostname: 10.0.0.10
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        folder: Targets
        esxi_hostname: 10.0.0.12
        name: CTF-SWIFT-SECURE
        template: ubuntu1604-12
        state: poweredon
        wait_for_ip_address: yes
        networks:
          - name: CTF-SecureNet
            ip: 172.16.1.199
            netmask: 255.255.255.0
            gateway: 172.16.1.1
            domain: bank.local
            dns_servers:
              - 8.8.8.8
              - 4.2.2.2
        customization:
          hostname: swift
          password: Sh73PJ8eK4n4wH3a6hPQTJZq
          dns_servers:
            - 8.8.8.8
            - 4.2.2.2