- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Provision participant DHCP from template
      vmware_guest:
        hostname: 10.1.0.199
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        esxi_hostname: 10.1.0.201
        name: CTF-RED-DHCP
        folder: Management
        template: ctf-win2012r2-standard
        state: poweredon
        wait_for_ip_address: yes
        networks:
          - name: CTF-RedTeamNet
            ip: 192.168.50.2
            netmask: 255.255.255.0
            domain: ctf.local
            gateway: 192.168.50.1
        customization:
          hostname: redteam
          password: Sh73PJ8eK4n4wH3a6hPQTJZq
          dns_servers:
            - 8.8.8.8
            - 4.2.2.2
    - name: Provision Management DHCP from template
      vmware_guest:
        hostname: 10.1.0.199
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        esxi_hostname: 10.1.0.201
        name: CTF-MGMT-DHCP
        folder: Management
        template: ctf-win2012r2-standard-12
        state: poweredon
        wait_for_ip_address: yes
        networks:
          - name: VM Network
            ip: 10.0.0.7
            netmask: 255.255.255.0
            gateway: 10.0.0.1
            dns_servers:
              - 8.8.8.8
              - 4.2.2.2
        customization:
          hostname: mgmtdhcp
          password: Sh73PJ8eK4n4wH3a6hPQTJZq
          dns_servers:
            - 8.8.8.8
            - 4.2.2.2
