- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Provision Biz Domain DC2 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        cluster: CTF
        name: CTF-DC2-BIZ
        template: ctf-win2008r2-standard
        state: poweredon
        networks:
          - name: CTF-BizNet
            ip: 172.16.2.5
            netmask: 255.255.255.0
            gateway: 172.16.2.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 8.8.8.8
              - 4.2.2.2
        customization:
          hostname: dc2biz
          password: Sh73PJ8eK4n4wH3a6hPQTJZq
