- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Provision Corp Domain DC2 from template
      vmware_guest:
        hostname: 10.1.0.50
        username: ansible@vsphere.local
        password: 36yvXdAjLPCxH6ZqjRJaWBBtSAaePB5b
        validate_certs: no
        datacenter: Datacenter
        esxi_hostname: 10.1.0.200
        name: CTF-DC2-CORP
        template: ctf-win2008r2-standard
        state: poweredon
        hardware:
          memory_mb: 4096
          num_cpus: 2
        wait_for_ip_address: yes
        networks:
          - name: CTF-CorpNet
            ip: 172.16.1.51
            netmask: 255.255.255.0
            gateway: 172.16.1.1
            domain: mercytechhealthcare.local
            dns_servers:
              - 8.8.8.8
              - 4.2.2.2
        customization:
          hostname: dc2
          password: Sh73PJ8eK4n4wH3a6hPQTJZq
          dns_servers:
            - 8.8.8.8
            - 4.2.2.2
