- include_playbook: playbooks/vmware_vswitches.yml
- include_playbook: playbooks/vmware_firewall.yml
- include_playbook: playbooks/firewall.yml
#- include: playbooks/vmware_linuxtestbox.yml
- include_playbook: playbooks/vmware_dc1.corp.yml
- include_playbook: playbooks/vmware_dc2.corp.yml
- include_playbook: playbooks/dc1_corp.stage0.yml
- include_playbook: playbooks/dc2_corp.stage0.yml
- include_playbook: playbooks/vmware_exchange_cas.yml
- include_playbook: playbooks/vmware_files.yml
- include_playbook: playbooks/exchange.yml
- include_playbook: playbooks/fileserver.yml
#- include: playbooks/otherservers.yml
- include_playbook: playbooks/vmware_workstations.yml
- include_playbook: playbooks/set_workstation_autologin.yml
- include_playbook: playbooks/more_impact.yml
