- include: playbooks/vmware_vswitches.yml
- include: playbooks/vmware_firewall.yml
- include: playbooks/firewall.yml
- include: playbooks/vmware_linuxtestbox.yml
- include: playbooks/vmware_dc1.corp.yml
- include: playbooks/vmware_dc2.corp.yml
- include: playbooks/vmware_dc1.biz.yml
- include: playbooks/vmware_dc2.biz.yml
- include: playbooks/dc1_corp.stage0.yml
